---
# tasks file for locale
- name: set locale.gen file
  template: src=locale.gen.j2 dest=/etc/locale.gen
  when: ansible_os_family == "Debian"
  notify: generate locales

- name: set locale
  become: yes
  template: src=default.j2 dest=/etc/default/locale
  when: ansible_os_family == "Debian"
